/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'RPCSpec'
*******************************************************************************/
package org.gemoc.franca.protocol.lib.spec;

import org.franca.deploymodel.core.FDeployedTypeCollection;

/**
 * Accessor for deployment properties for 'RPCSpec' specification
 *
 * @deprecated use class org.gemoc.franca.protocol.lib.spec.RPCSpec.TypeCollectionPropertyAccessor instead
 */
public class RPCSpecTypeCollectionPropertyAccessor
	extends org.gemoc.franca.protocol.lib.spec.RPCSpec.TypeCollectionPropertyAccessor
	implements org.gemoc.franca.protocol.lib.spec.RPCSpec.Enums
{
	public RPCSpecTypeCollectionPropertyAccessor(FDeployedTypeCollection target) {
		super(target);
	}
}
   
