/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'RPCSpec'
*******************************************************************************/
package org.gemoc.franca.protocol.lib.spec;

import org.franca.deploymodel.core.FDeployedInterface;

/**
 * Accessor for deployment properties for 'RPCSpec' specification
 *
 * @deprecated use class org.gemoc.franca.protocol.lib.spec.RPCSpec.InterfacePropertyAccessor instead
 */
public class RPCSpecInterfacePropertyAccessor
	extends org.gemoc.franca.protocol.lib.spec.RPCSpec.InterfacePropertyAccessor
	implements org.gemoc.franca.protocol.lib.spec.RPCSpec.Enums
{
	public RPCSpecInterfacePropertyAccessor(FDeployedInterface target) {
		super(target);
	}
}
   
