/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'WsJsonRpcSpec'
*******************************************************************************/
package org.gemoc.franca.protocol.lib.spec;

import org.franca.deploymodel.core.FDeployedTypeCollection;

/**
 * Accessor for deployment properties for 'WsJsonRpcSpec' specification
 *
 * @deprecated use class org.gemoc.franca.protocol.lib.spec.WsJsonRpcSpec.TypeCollectionPropertyAccessor instead
 */
public class WsJsonRpcSpecTypeCollectionPropertyAccessor
	extends org.gemoc.franca.protocol.lib.spec.WsJsonRpcSpec.TypeCollectionPropertyAccessor
	implements org.gemoc.franca.protocol.lib.spec.WsJsonRpcSpec.Enums
{
	public WsJsonRpcSpecTypeCollectionPropertyAccessor(FDeployedTypeCollection target) {
		super(target);
	}
}
   
