/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'WsJsonRpcSpec'
*******************************************************************************/
package org.gemoc.franca.protocol.lib.spec;

import org.franca.deploymodel.core.FDeployedInterface;

/**
 * Accessor for deployment properties for 'WsJsonRpcSpec' specification
 *
 * @deprecated use class org.gemoc.franca.protocol.lib.spec.WsJsonRpcSpec.InterfacePropertyAccessor instead
 */
public class WsJsonRpcSpecInterfacePropertyAccessor
	extends org.gemoc.franca.protocol.lib.spec.WsJsonRpcSpec.InterfacePropertyAccessor
	implements org.gemoc.franca.protocol.lib.spec.WsJsonRpcSpec.Enums
{
	public WsJsonRpcSpecInterfacePropertyAccessor(FDeployedInterface target) {
		super(target);
	}
}
   
