# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: mvn -B install --file pom.xml
      
    - name: Integration tests
      run: mvn -B verify --file org.gemoc.franca.protocol.gen.plugin.it.test/pom.xml  
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()  # always run even if the previous step fails
      with:
        files: "**/target/surefire-reports/TEST-*.xml"
    
    - name: Stage result files
      run: mkdir staging && cp */target/*.jar staging && cp examples/*/target/*.jar staging 
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging